# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3002fa6bc44c62ef6c870fdfa1291b9ba0c5c22616adf65a9997047f8115c8c61d250ef75a8a822ac46550446f5b17e63019d7226130e43d1c606a04d9abe4f0

test:
  secret_key_base: e2f49183fc68c73389cd40987d73d98e07537b5f01dfb29430029192e305d4d309d1035a959c9e306534886d181b7cd3ec697970b40588ef1830c0549d75a41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
